%[text] # Geospatial Data Analysis and Visualization
%[text:tableOfContents]{"heading":"Table of Contents"}
%%
%[text] ## Import Data (Excel)
%[text] Import the data from tsunamis.xlsx. Use the Import Data tool or Live task to automatically generate the code you need.
%%\ Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
% Auto-generated by MATLAB on 22-Apr-2026 11:09:17

%%\ Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 20);

% Specify sheet and range
opts.Sheet = "Sheet1";
opts.DataRange = "A2:T163";

% Specify column names and types
opts.VariableNames = ["Latitude", "Longitude", "Year", "Month", "Day", "Hour", "Minute", "Second", "ValidityCode", "Validity", "CauseCode", "Cause", "EarthquakeMagnitude", "Country", "Location", "MaxHeight", "IidaMagnitude", "Intensity", "NumDeaths", "DescDeaths"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "categorical", "double", "categorical", "double", "categorical", "categorical", "double", "double", "double", "double", "double"];

% Specify variable properties
opts = setvaropts(opts, ["Validity", "Cause", "Country", "Location"], "EmptyFieldRule", "auto");

% Import the data
tsunamis = readtable("tsunamis.xlsx", opts, "UseExcel", false);


%%\ Clear temporary variables
clear opts
%[text] You can also read data in directly from suitable online locations! See the [ChesapeakeBuoyData](<file:..\\..\\..\\..\\..\\..\\MATLAB Drive\\3_Demos\\ChesapeakeBuoyData>) demo for an example!
%%
%[text] ## Visualize Data
%[text] Quickly visualize data on a geographic axes. 
figure
geobubble(tsunamis.Latitude,tsunamis.Longitude,tsunamis.Intensity,tsunamis.Cause)

geolimits([-52 73],[-253 -17])
%%
%[text] Make your map more informative while still being digestible. Filter out the "undefined" cause tsunamis
indx = ismissing(tsunamis.Cause); % or put all the logical indexing in 1 line
tsunamis(indx,:) = [];

%[text] Add a few interactive Live controls for minimum tsunami size and validity code. View only tsunamis of one cause type.

minMagnitude = 4; %[control:slider:08ed]{"position":[16,17]}

unique(tsunamis.Cause)
cause = "Earthquake and Landslide"; %[control:dropdown:0302]{"position":[9,35]}

indxData = tsunamis.Cause == cause & tsunamis.Intensity >= minMagnitude;

%[text] Plot geospatial bubbles sized by intensity and colored by cause.
figure
geobubble(tsunamis.Latitude(indxData),tsunamis.Longitude(indxData),...
    tsunamis.Intensity(indxData),tsunamis.Cause(indxData))
%[text] Use a blue-green basemap for geographic context.
geobasemap('colorterrain')
%[text] Add a title showing the span of years in the dataset.
title({'Tsunamis by Cause'; [num2str(min(tsunamis.Year)),' - ', num2str(max(tsunamis.Year))]})
%%
%[text] ## Import Data (shape file, netcdf)
%[text] Read land area features from a shapefile into a GeoTable
land = readgeotable('landareas.shp');
%[text] Create a subset by excluding the 4th record (keep 1-3 and 5-end).
subland = land([1:3,5:end],:);
%[text] Create a projected CRS using ESRI code 102030.
proj = projcrs(32647);


figure
h = newmap(proj);
geoplot(subland,FaceColor="blue")
geolimits([25 50],[125 150])

hold on

geoscatter(tsunamis.Latitude,tsunamis.Longitude)
%[text] What if we want the map to fill up more of the figure and reduce the whitespace on the borders? Try these commands:
%[text] ```matlabCodeExample
%[text] set(h,'MapLayout','maximized')
%[text] set(h,'MapLayout','cartographic')
%[text] ```
%[text] 
%[text] 
%[text] 
%%
%[text] ## Convert Scattered Data to a Raster Grid
load ("oceanDepth.mat")

[Z, R] = geoloc2grid(oceanDepth.lat,oceanDepth.lon,oceanDepth.depth,1);
%[text] If your data are scattered across an irregular grid (non-uniform sampling intervals) use [scatteredInterpolant](https://www.mathworks.com/help/matlab/ref/scatteredinterpolant.html).
f = figure;
tiledlayout(1,2);
nexttile
newmap
geoscatter(oceanDepth.lat,oceanDepth.lon,20,oceanDepth.depth,"filled")


nexttile
newmap
geopcolor(Z,R)

h = axes(f,"Visible","off");
colormap([1 1 1; flipud(abyss)])
colorbar(h,'southoutside')
clim([0 max(oceanDepth.depth)])
sgtitle(f,'Ocean Depth (m)')
%%
%[text] ## Map with Georeferenced Image
info = georasterinfo("20240116120000-0h-wave-fc.grib2");
[A,R] = readgeoraster("20240116120000-0h-wave-fc.grib2","Bands",1);

land = imread("landOcean.jpg");
Rland = georefcells([-90 90],[-180 180],size(land),"ColumnsStartFrom","north");

proj = projcrs(102030,Authority="ESRI"); % lambert projection for SE Asia

figure
newmap(proj)
geoimage(land,Rland)
hold on

geopcolor(A,R)
geoscatter(tsunamis.Latitude,tsunamis.Longitude,100,'filled','k')


colormap(parula(12))
colorbar
geolimits([25 50],[125 150])

%[appendix]{"version":"1.0"}
%---
%[metadata:styles]
%   data: {"heading1":{"color":"#268cdd","fontFamily":"Trebuchet MS"},"heading2":{"bold":true,"color":"#edb120","fontFamily":"Trebuchet MS","italic":false,"underline":false},"heading3":{"bold":true,"color":"#ffffff","fontFamily":"Trebuchet MS","italic":false,"underline":false},"referenceBackgroundColor":"#333333","title":{"color":"#f57729"}}
%---
%[metadata:view]
%   data: {"layout":"inline"}
%---
%[control:slider:08ed]
%   data: {"defaultValue":0,"label":"minMagnitude","max":10,"min":0,"run":"Section","runOn":"ValueChanging","step":1}
%---
%[control:dropdown:0302]
%   data: {"defaultValue":"\"Earthquake\"","itemLabels":["Earthquake","Earthquake and Landslide","Landslide","Meteorological","Unknown Cause","Volcano","Volcano and Landslide"],"items":["\"Earthquake\"","\"Earthquake and Landslide\"","\"Landslide\"","\"Meteorological\"","\"Unknown Cause\"","\"Volcano\"","\"Volcano and Landslide\""],"label":"cause","run":"Section"}
%---
